registry:
    restart: always
    image: registry:2
    ports:
        - 5000:5000
    environment:
        - REGISTRY_AUTH_TOKEN_AUTOREDIRECT=false
        - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/server.crt
        - REGISTRY_HTTP_TLS_KEY=/certs/server.key
        - REGISTRY_AUTH=token
        - REGISTRY_AUTH_TOKEN_REALM=http://OAUTH_SERVER_IP:OAUTH_SERVER_PORT/oauth/auth/token
        - REGISTRY_AUTH_TOKEN_SERVICE=registry
        - REGISTRY_AUTH_TOKEN_ISSUER=oauth_server
        - REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/certs/server.crt
    volumes:
        - /certs:/certs